services:

  frontend:
    build:
      context: ./todo-ngxs
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./TodoApp
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: todo-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TodoDb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TodoDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: